- block:
    - name: Checking rabbitmq service
      service:
        name: rabbitmq-server
        state: started
  rescue:
    - include_tasks: "{{ ansible_os_family }}.yml"
    - include_tasks: main.yml

- name: Updating /etc/rabbitmq/rabbitmq-env.conf
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  notify: Restart rabbitmq-server

- include_tasks: clustering.yml
