- block:
    - name: Checking rabbitmq service
      service:
        name: rabbitmq-server
        state: started
      changed_when: false
  rescue:
    - include_tasks: "{{ ansible_os_family }}.yml"
    - include_tasks: main.yml

- name: Updating /etc/rabbitmq/rabbitmq-env.conf
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rabbitmq/{{ item }}"
  with_items:
    - rabbitmq-env.conf
    - rabbitmq.config
  notify: Restart rabbitmq-server

- include_tasks: clustering.yml
- include_tasks: plugins.yml

- block:
    - include_tasks: users.yml
    - include_tasks: vhosts.yml
  when: inventory_hostname == groups['all']|first
